apiVersion: v1
kind: PersistentVolume
metadata:
  name: webook-mysql-pvc
spec:
  storageClassName: record
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  # 持久卷的主机路径配置
  hostPath:
    path: "/mnt/data"